from binary_tree import BinaryTree

string_tree = BinaryTree('A')
string_tree.insert('B')
string_tree.insert('C')
string_tree.insert('D')
string_tree.insert('F')
string_tree.insert('E')
print(string_tree.search("E"))
print(string_tree.search('Z'))
print(string_tree)

string_tree2 = BinaryTree('B')
string_tree2.insert('A')
string_tree2.insert('C')
string_tree2.insert('E')
string_tree2.insert('D')
string_tree2.insert('F')
print(string_tree2)

integer_tree = BinaryTree(3)
integer_tree.insert(2)
integer_tree.insert(5)
print(integer_tree.search(10))
integer_tree.insert(1)
integer_tree.insert(3)
integer_tree.insert(3)
integer_tree.insert(4)
integer_tree.insert(5)
integer_tree.insert(10)
integer_tree.insert(6)
print(integer_tree.search(10))
print(integer_tree)